# syntax=docker/dockerfile:1.7-labs
# This image will be published as dspace/dspace-dependencies
# The purpose of this image is to make the build for dspace/dspace run faster
#

# This Dockerfile uses JDK21 by default.
# To build with other versions, use "--build-arg JDK_VERSION=[value]"
ARG JDK_VERSION=21

# Step 1 - Download all Dependencies
FROM docker.io/maven:3-eclipse-temurin-${JDK_VERSION} AS build
ARG TARGET_DIR=dspace-installer
WORKDIR /app
# Create the 'dspace' user account & home directory
RUN useradd -m -d /home/dspace -s /bin/bash dspace \
    && mkdir -p /app/dspace
RUN chown -Rv dspace: /app

# Switch to dspace user & run below commands as that user
USER dspace

# This next part may look odd, but it speeds up the build of this image *significantly*.
# Copy ONLY the POMs to this image (from local machine). This will allow us to download all dependencies *without*
# performing any code compilation steps.

# Parent POM
COPY --chown=dspace --parents pom.xml **/pom.xml /app/dspace/

ENV MVN_FLAGS="-B -P-assembly -P-test-environment -Denforcer.skip=true -Dcheckstyle.skip=true -Dlicense.skip=true -Dxjc.skip=true -Dxml.skip=true"
RUN --mount=type=cache,target=/root/.m2 mvn -f /app/dspace/pom.xml --fail-never -ntp verify ${MVN_FLAGS}

# Clear the contents of the /app directory (including all maven target folders), so no artifacts remain.
# This ensures when dspace:dspace is built, it will use the Maven local cache (~/.m2) for dependencies
USER root
RUN rm -rf /app/*

# Switch to initial user to drop root privileges (DL3002)
USER dspace
